# Stage 1 のコンテナ（アプリケーションをビルド）
FROM golang:1.24.0-alpine3.21 as builder
COPY ./main.go ./
RUN CGO_ENABLED=0 go build -o /go-app ./main.go

# Stage 2 のコンテナ（ビルドしたバイナリを内包した実行用コンテナを作成）
FROM scratch
# Stage 1 でビルドした成果物をコピー
COPY --from=builder /go-app .
ENTRYPOINT ["./go-app"]
