# Stage 1 のコンテナ（アプリケーションをコンパイル）
FROM golang:1.24.0-alpine3.21 as builder
COPY ./main.go ./
RUN go build -o /go-app ./main.go

# Stage 2 のコンテナ（コンパイルしたバイナリを内包した実行用コンテナを作成）
FROM alpine:3.21
# Stage 1 でコンパイルした成果物をコピー
COPY --from=builder /go-app .
ENTRYPOINT ["./go-app"]
